---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-http-multiplexer
  namespace: default
  labels:
    app: k8s-http-multiplexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-http-multiplexer
  template:
    metadata:
      labels:
        app: k8s-http-multiplexer
    spec:
      containers:
        - name: k8s-http-multiplexer
          image: docker.io/bilalcaliskan/k8s-http-multiplexer:latest
          args: ["-configFilePath", "/opt/config/config.yaml"]
          command: ["./main"]
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config
              mountPath: "/opt/config"
              readOnly: true
      serviceAccountName: multiplexer
      volumes:
        - name: config
          configMap:
            name: k8s-http-multiplexer-config