apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-b
  namespace: default
  labels:
    app: nginx-b
    foo: bar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-b
  template:
    metadata:
      labels:
        app: nginx-b
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80